### ISSUE TITLE
Resetting possible selections

### ISSUE THREAD

**Issue by namednil** [FlorianPusse/Lingoturk#2] opened 2016-06-27 17:43 UTC
If you reset the lists when creating a new experiment, the possible selections aren't reset as well.

**Comment by FlorianPusse** [comment] 2016-07-06 19:58
Nice observation. This bug is resolved in the newest version. (b86822dc8f6788edcd1c7773cbf9ed51e608e369)

As the problem is resolved, I'll close that issue. Thanks for reporting it!

**Closed as completed** 2016-07-06 19:58 UTC
Labels: bug
